# Generated by Django 6.0.5 on 2026-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/', verbose_name='Imagen del proyecto'),
        ),
    ]
